#cloud-config
packages:
  - curl
  - git
  - apt-transport-https
  - ca-certificates
  - gpg
users:
  - name: cluster
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAHjDvjzuw/8FXl61n2j3GwQWvESYyKpa/qC9XwU+HkV alex@seven
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

write_files:
  - path: /root/.ssh/id_rsa
    content: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      $(WORKER_SSH_PRIVKEY) 
      -----END OPENSSH PRIVATE KEY-----
    permissions: "0600"

runcmd:
  - apt-get update -y
  -  # wait for the master node to be ready by trying to connect to it
  - until curl -k https://10.0.1.1:6443; do sleep 5; done
  - modprobe overlay
  - modprobe br_netfilter
  - |
    tee /etc/sysctl.d/kubernetes.conf<<EOF
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    net.ipv4.ip_forward = 1
    EOF
  - |
    tee /etc/modules-load.d/k8s.conf <<EOF
    overlay
    br_netfilter
    EOF
  - sudo sysctl --system
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
    https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable"
  - tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get install containerd.io
  - mkdir -p /etc/containerd
  - containerd config default | sudo tee /etc/containerd/config.toml
  - systemctl restart containerd
  - systemctl enable containerd
  - systemctl status containerd
  - sh -c "echo 'net.ipv4.ip_forward = 1' >> /etc/sysctl.conf"
  - sysctl -p
  - mkdir -p -m 755 /etc/apt/keyrings
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
  - apt-get update -y
  - systemctl enable --now kubelet
  -
