#cloud-config
packages:
  - curl
  - git
  - containerd
  - kubernetes
users:
  - name: cluster
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAHjDvjzuw/8FXl61n2j3GwQWvESYyKpa/qC9XwU+HkV alex@seven
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

write_files:
  - path: /root/.ssh/id_rsa
    content: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      $(WORKER_SSH_PRIVKEY) 
      -----END OPENSSH PRIVATE KEY-----
    permissions: "0600"

runcmd:
  - apt-get update -y
  -  # wait for the master node to be ready by trying to connect to it
  - until curl -k https://10.0.1.1:6443; do sleep 5; done
